#!/bin/sh

for program in picom polybar xbanish; do
    systemctl --user start $program
done
nitrogen --restore
sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 1
bspc config window_gap 10

# Use the Ayu colour scheme
bspc config normal_border_color '#737D87'
bspc config focused_border_color '#73D0FF'
bspc config presel_feedback_color '#73D0FF'

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Emacs and Zathura need to be explicitly told to tile, for some reason.
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
